import fs from 'node:fs';
import path from 'node:path';

const domainDir = path.resolve('../domain_operators');
const files = fs.readdirSync(domainDir).filter(f => f.endsWith('.md')).sort();

const domainNames = {
  '01_business_model.md': '商业模式与战略突围',
  '02_game_design.md': '游戏机制与系统规则设计',
  '03_narrative_storytelling.md': '剧作编剧与长篇内容叙事',
  '04_hardware_physical_product.md': '实体产品、硬件与交互设计',
  '05_organization_governance.md': '组织机制与治理博弈',
  '06_deep_tech_architecture.md': '技术架构与底层算法攻关',
  '07_brand_marketing_memes.md': '品牌营销与迷因破圈',
  '08_personal_strategy.md': '高难度个人战略与人生重大博弈',
  '09_math_proof_formal_reasoning.md': '数学证明与形式推理'
};

const operators = [];
const catalog = [];

for (const file of files) {
  const domainName = domainNames[file] || file.replace('.md', '');
  const filePath = path.join(domainDir, file);
  const content = fs.readFileSync(filePath, 'utf8');
  const lines = content.split('\n');

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i].trim();
    if (line.startsWith('### ')) {
      const parts = line.replace('### ', '').trim().split(/\s+/);
      const operator_id = parts[0];
      const name = parts.slice(1).join(' ');
      
      const pLines = [];
      for (let j = i + 1; j < lines.length; j++) {
        if (lines[j].startsWith('### ') || lines[j].startsWith('---')) break;
        pLines.push(lines[j]);
      }
      const prompt = pLines.join('\n').trim();
      
      const paragraphs = prompt.split('\n\n').map(p => p.trim()).filter(Boolean);
      const firstPara = paragraphs[0] || '';
      const brief = firstPara.length > 120 ? firstPara.slice(0, 118) + '…' : firstPara;

      operators.push({
        operator_id,
        family: domainName,
        name,
        prompt,
        enabled: true
      });

      catalog.push({
        operator_id,
        name,
        domain: domainName,
        summary: brief
      });
    }
  }
}

console.log(`Parsed ${files.length} files, ${operators.length} domain operators.`);

const outputContent = `// Auto-generated by scripts/compile_domain_operators.mjs
// Do not edit manually.

export const DOMAIN_OPERATORS_VERSION = 'domain-operators-v1';

export const domainCatalog = ${JSON.stringify(catalog, null, 2)};

export const domainOperators = ${JSON.stringify(operators, null, 2)};

export const domainOperatorsMap = new Map(domainOperators.map(o => [o.operator_id, o]));
`;

fs.writeFileSync(path.resolve('src/domain_operators.mjs'), outputContent, 'utf8');
console.log('Successfully wrote src/domain_operators.mjs');
