// Auto-generated by scripts/compile_domain_operators.mjs
// Do not edit manually.

export const DOMAIN_OPERATORS_VERSION = 'domain-operators-v2-industry-lenses';

export const domainCatalog = [
  {
    "operator_id": "value_recipient_map",
    "name": "价值与付费者对齐",
    "domain": "商业模式与战略突围",
    "scope": "industry_general",
    "task_types": [
      "industry_reasoning"
    ],
    "applies_to": "任何需要明确谁使用、谁受益、谁付费的业务问题。",
    "excludes": "已经给定唯一付款方、且只讨论内部执行细节的任务。"
  },
  {
    "operator_id": "willingness_to_pay",
    "name": "支付意愿证据",
    "domain": "商业模式与战略突围",
    "scope": "industry_general",
    "task_types": [
      "industry_reasoning"
    ],
    "applies_to": "定价、收费方式、免费转付费或商业化可行性问题。",
    "excludes": "公益目标或明确不要求收入回收的项目。"
  },
  {
    "operator_id": "unit_economics_boundary",
    "name": "单位经济边界",
    "domain": "商业模式与战略突围",
    "scope": "industry_general",
    "task_types": [
      "industry_reasoning"
    ],
    "applies_to": "规模增长、获客、履约成本和毛利是否可持续的问题。",
    "excludes": "尚未确定基本交付物、无法定义一次交易或一次服务的探索。"
  },
  {
    "operator_id": "acquisition_retention_split",
    "name": "获客与留存分离",
    "domain": "商业模式与战略突围",
    "scope": "industry_general",
    "task_types": [
      "industry_reasoning"
    ],
    "applies_to": "用户增长、渠道效率、复购或使用频率问题。",
    "excludes": "一次性交付且没有复购、续期或持续使用目标的业务。"
  },
  {
    "operator_id": "switching_friction",
    "name": "真实切换成本",
    "domain": "商业模式与战略突围",
    "scope": "industry_general",
    "task_types": [
      "industry_reasoning"
    ],
    "applies_to": "竞争替代、客户迁移、产品换代和存量市场进入问题。",
    "excludes": "用户没有现有替代方案、也没有既有流程可迁移的全新需求。"
  },
  {
    "operator_id": "incentive_compatibility",
    "name": "交易激励一致性",
    "domain": "商业模式与战略突围",
    "scope": "industry_general",
    "task_types": [
      "industry_reasoning"
    ],
    "applies_to": "平台、多方合作、代理销售、供应链或任何参与方行为会影响结果的业务。",
    "excludes": "单一主体能够独立完成且不存在委托关系的内部任务。"
  },
  {
    "operator_id": "bottleneck_before_scale",
    "name": "扩张前瓶颈",
    "domain": "商业模式与战略突围",
    "scope": "industry_general",
    "task_types": [
      "industry_reasoning"
    ],
    "applies_to": "计划扩大用户、区域、产能、团队或产品线的问题。",
    "excludes": "当前任务只是验证是否有人需要产品，尚未进入扩张讨论。"
  },
  {
    "operator_id": "reversible_business_test",
    "name": "可逆商业试验",
    "domain": "商业模式与战略突围",
    "scope": "industry_general",
    "task_types": [
      "industry_reasoning"
    ],
    "applies_to": "高不确定的新市场、新定价、新客群或合作方式选择。",
    "excludes": "已经涉及不可逆监管承诺、安全风险或大额长期合同的决定。"
  },
  {
    "operator_id": "flow_load_curve",
    "name": "心流负荷曲线",
    "domain": "游戏机制与系统规则设计",
    "scope": "industry_general",
    "task_types": [
      "industry_reasoning"
    ],
    "applies_to": "任何需要安排挑战强度、学习节奏和持续投入感的游戏。",
    "excludes": "没有玩家操作、选择或理解过程的纯展示内容。"
  },
  {
    "operator_id": "meaningful_choice_density",
    "name": "有效选择密度",
    "domain": "游戏机制与系统规则设计",
    "scope": "industry_general",
    "task_types": [
      "industry_reasoning"
    ],
    "applies_to": "任何强调玩家选择、资源分配或重复游玩的游戏。",
    "excludes": "设计目标明确是短时放松、且主要价值来自无决策的感官反馈时。"
  },
  {
    "operator_id": "feedback_traceability",
    "name": "反馈可归因性",
    "domain": "游戏机制与系统规则设计",
    "scope": "industry_general",
    "task_types": [
      "industry_reasoning"
    ],
    "applies_to": "任何玩家行动会产生数值、状态、进度或叙事结果的游戏。",
    "excludes": "结果刻意不可知且不可推理就是核心体验的局部段落。"
  },
  {
    "operator_id": "visible_compounding",
    "name": "复利快感检验",
    "domain": "游戏机制与系统规则设计",
    "scope": "industry_general",
    "task_types": [
      "industry_reasoning"
    ],
    "applies_to": "成长、经营、收集、解谜效率或任何允许玩家建立长期增益的游戏。",
    "excludes": "追求固定能力、每局完全重置且不希望效率加速的体验。"
  },
  {
    "operator_id": "progression_runway",
    "name": "成长跑道检查",
    "domain": "游戏机制与系统规则设计",
    "scope": "industry_general",
    "task_types": [
      "industry_reasoning"
    ],
    "applies_to": "存在长期属性、关卡、能力、资源或内容解锁进度的游戏。",
    "excludes": "单次体验很短且没有持续成长目标的作品。"
  },
  {
    "operator_id": "dominant_strategy_check",
    "name": "支配策略检查",
    "domain": "游戏机制与系统规则设计",
    "scope": "industry_general",
    "task_types": [
      "industry_reasoning"
    ],
    "applies_to": "任何提供两个以上可重复选择、组合或发展方向的游戏。",
    "excludes": "明确设计为只有一种解法的教学步骤或短篇固定流程。"
  },
  {
    "operator_id": "failure_recovery",
    "name": "失败与恢复路径",
    "domain": "游戏机制与系统规则设计",
    "scope": "industry_general",
    "task_types": [
      "industry_reasoning"
    ],
    "applies_to": "任何允许犯错、损失资源、卡住或未达成目标的游戏。",
    "excludes": "失败即结束且一次尝试本身极短、重新开始没有成本的局部挑战。"
  },
  {
    "operator_id": "returnability",
    "name": "中断后回归",
    "domain": "游戏机制与系统规则设计",
    "scope": "industry_general",
    "task_types": [
      "industry_reasoning"
    ],
    "applies_to": "可能跨天游玩、单局较长、系统较多或允许长期积累的游戏。",
    "excludes": "数分钟内一次完成且不会保存状态的体验。"
  },
  {
    "operator_id": "character_goal_pressure",
    "name": "角色目标与压力",
    "domain": "剧作编剧与长篇内容叙事",
    "scope": "industry_general",
    "task_types": [
      "industry_reasoning"
    ],
    "applies_to": "由人物行动推动的影视、小说、互动叙事和长篇内容。",
    "excludes": "没有人物主体、只做事实说明的内容。"
  },
  {
    "operator_id": "causal_story_chain",
    "name": "叙事因果链",
    "domain": "剧作编剧与长篇内容叙事",
    "scope": "industry_general",
    "task_types": [
      "industry_reasoning"
    ],
    "applies_to": "任何要求事件前后具有可信联系的叙事。",
    "excludes": "明确以碎片联想、梦境或无因果并置为主要形式的实验作品。"
  },
  {
    "operator_id": "information_release",
    "name": "信息释放顺序",
    "domain": "剧作编剧与长篇内容叙事",
    "scope": "industry_general",
    "task_types": [
      "industry_reasoning"
    ],
    "applies_to": "悬念、理解、发现过程会影响体验的叙事。",
    "excludes": "信息顺序不影响理解的工具性说明。"
  },
  {
    "operator_id": "viewpoint_knowledge",
    "name": "视角与可知范围",
    "domain": "剧作编剧与长篇内容叙事",
    "scope": "industry_general",
    "task_types": [
      "industry_reasoning"
    ],
    "applies_to": "需要选择叙述视角、切换人物或控制信息可信度的内容。",
    "excludes": "完全客观、无人物视角的简短记录。"
  },
  {
    "operator_id": "tension_variation",
    "name": "张力变化",
    "domain": "剧作编剧与长篇内容叙事",
    "scope": "industry_general",
    "task_types": [
      "industry_reasoning"
    ],
    "applies_to": "需要维持阅读、观看或游玩投入的中长篇叙事。",
    "excludes": "只有单一信息点的极短内容。"
  },
  {
    "operator_id": "setup_payoff",
    "name": "伏笔与兑现",
    "domain": "剧作编剧与长篇内容叙事",
    "scope": "industry_general",
    "task_types": [
      "industry_reasoning"
    ],
    "applies_to": "需要回收前文信息、承诺或情绪期待的叙事。",
    "excludes": "刻意拒绝闭合、且这种未完成感就是主题的作品。"
  },
  {
    "operator_id": "character_consistency",
    "name": "人物一致与变化",
    "domain": "剧作编剧与长篇内容叙事",
    "scope": "industry_general",
    "task_types": [
      "industry_reasoning"
    ],
    "applies_to": "人物需要在较长时间内保持可信并发生变化的叙事。",
    "excludes": "人物只是无人格的信息载体。"
  },
  {
    "operator_id": "audience_orientation",
    "name": "受众理解定位",
    "domain": "剧作编剧与长篇内容叙事",
    "scope": "industry_general",
    "task_types": [
      "industry_reasoning"
    ],
    "applies_to": "人物、时间线、规则或背景较复杂的叙事。",
    "excludes": "复杂和迷失本身是经过验证的核心体验时。"
  },
  {
    "operator_id": "real_use_context",
    "name": "真实使用情境",
    "domain": "实体产品、硬件与交互设计",
    "scope": "industry_general",
    "task_types": [
      "industry_reasoning"
    ],
    "applies_to": "任何需要人在现实环境中拿取、安装、操作或维护的产品。",
    "excludes": "完全没有实体接触和环境约束的纯软件任务。"
  },
  {
    "operator_id": "affordance_clarity",
    "name": "操作示意清晰度",
    "domain": "实体产品、硬件与交互设计",
    "scope": "industry_general",
    "task_types": [
      "industry_reasoning"
    ],
    "applies_to": "存在按钮、把手、接口、开合、插拔、方向或状态切换的产品。",
    "excludes": "用户不会直接操作、只由专业设备自动执行的内部部件。"
  },
  {
    "operator_id": "load_path",
    "name": "受力与传递路径",
    "domain": "实体产品、硬件与交互设计",
    "scope": "industry_general",
    "task_types": [
      "industry_reasoning"
    ],
    "applies_to": "承受重量、冲击、振动、热量、压力或反复动作的实体设计。",
    "excludes": "没有显著物理载荷的外观讨论。"
  },
  {
    "operator_id": "tolerance_stack",
    "name": "公差累积",
    "domain": "实体产品、硬件与交互设计",
    "scope": "industry_general",
    "task_types": [
      "industry_reasoning"
    ],
    "applies_to": "多个零件装配、运动配合、密封、定位或批量生产问题。",
    "excludes": "单件手工原型且暂不要求重复制造的探索。"
  },
  {
    "operator_id": "safe_failure",
    "name": "安全失效",
    "domain": "实体产品、硬件与交互设计",
    "scope": "industry_general",
    "task_types": [
      "industry_reasoning"
    ],
    "applies_to": "故障可能伤人、损坏周边、丢失关键数据或阻断基本功能的产品。",
    "excludes": "失败后没有实质损失、可以立即重试的一次性模型。"
  },
  {
    "operator_id": "maintenance_access",
    "name": "维护可达性",
    "domain": "实体产品、硬件与交互设计",
    "scope": "industry_general",
    "task_types": [
      "industry_reasoning"
    ],
    "applies_to": "需要清洁、更换耗材、校准、维修或长期使用的产品。",
    "excludes": "使用寿命很短且按计划整体更换的低风险物品。"
  },
  {
    "operator_id": "lifecycle_tradeoff",
    "name": "生命周期取舍",
    "domain": "实体产品、硬件与交互设计",
    "scope": "industry_general",
    "task_types": [
      "industry_reasoning"
    ],
    "applies_to": "材料、能耗、耐久、成本、可修复性和回收之间需要权衡的产品。",
    "excludes": "只验证短期功能、尚未进入材料和量产决策的概念模型。"
  },
  {
    "operator_id": "measurable_prototype",
    "name": "可测量原型",
    "domain": "实体产品、硬件与交互设计",
    "scope": "industry_general",
    "task_types": [
      "industry_reasoning"
    ],
    "applies_to": "硬件概念尚未验证、存在关键人体或物理假设的设计。",
    "excludes": "已经有稳定量产数据、当前只处理明确缺陷的任务。"
  },
  {
    "operator_id": "decision_rights",
    "name": "决策权边界",
    "domain": "组织机制与治理博弈",
    "scope": "industry_general",
    "task_types": [
      "industry_reasoning"
    ],
    "applies_to": "多人协作中出现等待、越权、重复审批或无人拍板的问题。",
    "excludes": "单人能够独立决定并执行的任务。"
  },
  {
    "operator_id": "incentive_behavior",
    "name": "激励与实际行为",
    "domain": "组织机制与治理博弈",
    "scope": "industry_general",
    "task_types": [
      "industry_reasoning"
    ],
    "applies_to": "考核、奖金、晋升、配额或声誉影响成员行为的组织。",
    "excludes": "没有持续参与者、也不存在评价和资源分配的短期协作。"
  },
  {
    "operator_id": "information_path",
    "name": "信息到达路径",
    "domain": "组织机制与治理博弈",
    "scope": "industry_general",
    "task_types": [
      "industry_reasoning"
    ],
    "applies_to": "决策质量受到层级汇报、跨部门传递或信息过滤影响的问题。",
    "excludes": "所有相关人员已经共享同一实时事实来源的简单协作。"
  },
  {
    "operator_id": "accountability_control",
    "name": "责任与控制能力",
    "domain": "组织机制与治理博弈",
    "scope": "industry_general",
    "task_types": [
      "industry_reasoning"
    ],
    "applies_to": "追责、授权、跨团队依赖和结果归属不清的问题。",
    "excludes": "结果完全由单一执行者控制的独立任务。"
  },
  {
    "operator_id": "conflict_resolution",
    "name": "冲突处理路径",
    "domain": "组织机制与治理博弈",
    "scope": "industry_general",
    "task_types": [
      "industry_reasoning"
    ],
    "applies_to": "不同目标、专业判断或资源需求会反复冲突的组织。",
    "excludes": "一次性的人际争执且不涉及重复协作机制。"
  },
  {
    "operator_id": "exception_handling",
    "name": "例外处理",
    "domain": "组织机制与治理博弈",
    "scope": "industry_general",
    "task_types": [
      "industry_reasoning"
    ],
    "applies_to": "规则经常被临时绕过、特殊审批越来越多的组织。",
    "excludes": "尚无稳定流程、所有情况都仍在探索期的团队。"
  },
  {
    "operator_id": "feedback_cadence",
    "name": "反馈周期匹配",
    "domain": "组织机制与治理博弈",
    "scope": "industry_general",
    "task_types": [
      "industry_reasoning"
    ],
    "applies_to": "目标周期、复盘频率和实际变化速度不一致的问题。",
    "excludes": "结果即时可见、无需跨周期调整的简单任务。"
  },
  {
    "operator_id": "reversible_governance",
    "name": "可逆治理试点",
    "domain": "组织机制与治理博弈",
    "scope": "industry_general",
    "task_types": [
      "industry_reasoning"
    ],
    "applies_to": "组织制度调整影响较大、但真实后果尚不确定的情况。",
    "excludes": "涉及法定责任、安全红线或不可逆人员伤害的决定。"
  },
  {
    "operator_id": "requirement_partition",
    "name": "需求分层",
    "domain": "技术架构与底层算法攻关",
    "scope": "industry_general",
    "task_types": [
      "industry_reasoning"
    ],
    "applies_to": "技术方案同时包含性能、一致性、成本、安全或可用性目标的问题。",
    "excludes": "需求已经单一明确、只需修复局部实现错误的任务。"
  },
  {
    "operator_id": "latency_budget",
    "name": "时延预算",
    "domain": "技术架构与底层算法攻关",
    "scope": "industry_general",
    "task_types": [
      "industry_reasoning"
    ],
    "applies_to": "用户请求、数据处理或跨服务链路存在响应时间目标的系统。",
    "excludes": "离线批处理且完成时间没有业务约束的任务。"
  },
  {
    "operator_id": "state_ownership",
    "name": "状态归属",
    "domain": "技术架构与底层算法攻关",
    "scope": "industry_general",
    "task_types": [
      "industry_reasoning"
    ],
    "applies_to": "多个服务、节点或区域都可能读取和修改同一业务状态的问题。",
    "excludes": "无持久状态的纯计算任务。"
  },
  {
    "operator_id": "failure_domain",
    "name": "故障域",
    "domain": "技术架构与底层算法攻关",
    "scope": "industry_general",
    "task_types": [
      "industry_reasoning"
    ],
    "applies_to": "分布式、依赖外部服务或要求持续可用的系统。",
    "excludes": "故障后可以整体重启且没有数据或时间损失的本地工具。"
  },
  {
    "operator_id": "consistency_semantics",
    "name": "一致性语义",
    "domain": "技术架构与底层算法攻关",
    "scope": "industry_general",
    "task_types": [
      "industry_reasoning"
    ],
    "applies_to": "数据可能并发修改、延迟复制或被多个位置观察的系统。",
    "excludes": "只追加且读取顺序完全不影响业务结果的独立日志。"
  },
  {
    "operator_id": "capacity_backlog",
    "name": "容量与积压",
    "domain": "技术架构与底层算法攻关",
    "scope": "industry_general",
    "task_types": [
      "industry_reasoning"
    ],
    "applies_to": "有队列、异步处理、突发流量或上下游速率差的系统。",
    "excludes": "请求量固定且所有工作同步完成的简单工具。"
  },
  {
    "operator_id": "observability_question",
    "name": "可观测性问题",
    "domain": "技术架构与底层算法攻关",
    "scope": "industry_general",
    "task_types": [
      "industry_reasoning"
    ],
    "applies_to": "系统出现慢、错、丢失或偶发异常但难以定位的问题。",
    "excludes": "原因已经由可重复测试明确定位的单点缺陷。"
  },
  {
    "operator_id": "migration_reversibility",
    "name": "迁移可逆性",
    "domain": "技术架构与底层算法攻关",
    "scope": "industry_general",
    "task_types": [
      "industry_reasoning"
    ],
    "applies_to": "更换存储、协议、模型、平台或核心数据结构的系统改造。",
    "excludes": "没有存量数据和在线用户的全新系统原型。"
  },
  {
    "operator_id": "audience_job",
    "name": "受众当前任务",
    "domain": "品牌营销与迷因破圈",
    "scope": "industry_general",
    "task_types": [
      "industry_reasoning"
    ],
    "applies_to": "需要确定传播对象、使用场景或信息重点的营销问题。",
    "excludes": "受众、场景和购买原因已经由可靠行为数据明确给定的执行任务。"
  },
  {
    "operator_id": "promise_evidence",
    "name": "承诺与证据",
    "domain": "品牌营销与迷因破圈",
    "scope": "industry_general",
    "task_types": [
      "industry_reasoning"
    ],
    "applies_to": "广告、品牌主张、销售页面和新品传播。",
    "excludes": "只传达时间、地点等无需说服的事实通知。"
  },
  {
    "operator_id": "message_distinction",
    "name": "信息区分度",
    "domain": "品牌营销与迷因破圈",
    "scope": "industry_general",
    "task_types": [
      "industry_reasoning"
    ],
    "applies_to": "同类产品表达相似、受众记不住差别的问题。",
    "excludes": "市场尚无相近替代、当前主要障碍是受众不知道品类存在。"
  },
  {
    "operator_id": "channel_context",
    "name": "渠道情境匹配",
    "domain": "品牌营销与迷因破圈",
    "scope": "industry_general",
    "task_types": [
      "industry_reasoning"
    ],
    "applies_to": "同一信息需要进入不同媒体、入口或线下触点的问题。",
    "excludes": "渠道固定且用户主动前来获取完整说明的单一场景。"
  },
  {
    "operator_id": "memory_retrieval",
    "name": "记忆与提取线索",
    "domain": "品牌营销与迷因破圈",
    "scope": "industry_general",
    "task_types": [
      "industry_reasoning"
    ],
    "applies_to": "品牌知名但购买时想不起、或传播看过却无法复述的问题。",
    "excludes": "一次性即时转化、用户无需未来回忆的通知。"
  },
  {
    "operator_id": "trust_risk",
    "name": "信任风险",
    "domain": "品牌营销与迷因破圈",
    "scope": "industry_general",
    "task_types": [
      "industry_reasoning"
    ],
    "applies_to": "健康、金融、隐私、高价格、长期承诺或陌生品牌传播。",
    "excludes": "低风险、可立即试用且失败成本接近零的轻量选择。"
  },
  {
    "operator_id": "behavior_path",
    "name": "行为路径",
    "domain": "品牌营销与迷因破圈",
    "scope": "industry_general",
    "task_types": [
      "industry_reasoning"
    ],
    "applies_to": "传播有明确注册、咨询、试用、购买或复购目标的问题。",
    "excludes": "只做公共信息覆盖且没有后续行为目标的内容。"
  },
  {
    "operator_id": "incremental_campaign_test",
    "name": "增量传播试验",
    "domain": "品牌营销与迷因破圈",
    "scope": "industry_general",
    "task_types": [
      "industry_reasoning"
    ],
    "applies_to": "需要判断某条信息、渠道或创意是否真正带来新增结果。",
    "excludes": "无法形成任何可比较组、也无法观察行为结果的纯曝光项目。"
  },
  {
    "operator_id": "objective_ownership",
    "name": "目标归属",
    "domain": "高难度个人战略与人生重大博弈",
    "scope": "industry_general",
    "task_types": [
      "industry_reasoning"
    ],
    "applies_to": "职业、学习、关系、迁移或长期投入中不确定自己为何选择的问题。",
    "excludes": "目标由紧急安全需要或明确法定义务决定的情况。"
  },
  {
    "operator_id": "downside_boundary",
    "name": "下行边界",
    "domain": "高难度个人战略与人生重大博弈",
    "scope": "industry_general",
    "task_types": [
      "industry_reasoning"
    ],
    "applies_to": "高不确定、高投入或结果分布很宽的个人决定。",
    "excludes": "损失很小、可立即恢复的日常选择。"
  },
  {
    "operator_id": "option_value",
    "name": "选择空间价值",
    "domain": "高难度个人战略与人生重大博弈",
    "scope": "industry_general",
    "task_types": [
      "industry_reasoning"
    ],
    "applies_to": "信息不足但很快要做决定、且部分承诺不可逆的情况。",
    "excludes": "拖延本身会造成更大不可逆损失的紧急决定。"
  },
  {
    "operator_id": "evidence_story_split",
    "name": "证据与自我叙事分离",
    "domain": "高难度个人战略与人生重大博弈",
    "scope": "industry_general",
    "task_types": [
      "industry_reasoning"
    ],
    "applies_to": "对机会、能力、关系或趋势的判断主要来自强烈感受和零散案例时。",
    "excludes": "已有充分重复数据、当前只需执行明确计划的任务。"
  },
  {
    "operator_id": "resource_allocation",
    "name": "资源配置",
    "domain": "高难度个人战略与人生重大博弈",
    "scope": "industry_general",
    "task_types": [
      "industry_reasoning"
    ],
    "applies_to": "时间、金钱、精力分散在多个长期目标之间的问题。",
    "excludes": "当前存在必须立即处理的单一危机。"
  },
  {
    "operator_id": "reversible_commitment",
    "name": "可逆承诺",
    "domain": "高难度个人战略与人生重大博弈",
    "scope": "industry_general",
    "task_types": [
      "industry_reasoning"
    ],
    "applies_to": "想尝试新职业、城市、合作或生活方式但不确定匹配度的选择。",
    "excludes": "试验会伤害他人权益、违反合同或制造不可逆安全风险的情况。"
  },
  {
    "operator_id": "feedback_horizon",
    "name": "反馈时间尺度",
    "domain": "高难度个人战略与人生重大博弈",
    "scope": "industry_general",
    "task_types": [
      "industry_reasoning"
    ],
    "applies_to": "努力与结果间隔较长、容易过早放弃或长期自我安慰的目标。",
    "excludes": "结果即时明确的简单任务。"
  },
  {
    "operator_id": "identity_cost",
    "name": "身份成本",
    "domain": "高难度个人战略与人生重大博弈",
    "scope": "industry_general",
    "task_types": [
      "industry_reasoning"
    ],
    "applies_to": "改变方向会威胁自我认同、社会评价或既有关系的问题。",
    "excludes": "选择与身份和长期关系无关的低成本日常决定。"
  },
  {
    "operator_id": "assumption_domain",
    "name": "定义域与假设检查",
    "domain": "数学证明与形式推理",
    "scope": "industry_general",
    "task_types": [
      "formal_reasoning"
    ],
    "applies_to": "需要证明的命题包含变量范围、连续性、独立性、有限性或其他前提。",
    "excludes": "没有待证命题、只要求经验方案或参数建议的任务。"
  },
  {
    "operator_id": "minimal_counterexample",
    "name": "最小反例",
    "domain": "数学证明与形式推理",
    "scope": "industry_general",
    "task_types": [
      "formal_reasoning"
    ],
    "applies_to": "全称命题可能错误，或需要定位证明在哪个最小结构上失败。",
    "excludes": "命题只涉及单个给定实例、无法定义规模或次序。"
  },
  {
    "operator_id": "invariant_or_measure",
    "name": "不变量或单调量",
    "domain": "数学证明与形式推理",
    "scope": "industry_general",
    "task_types": [
      "formal_reasoning"
    ],
    "applies_to": "离散操作、迭代过程、可达性或终止性证明。",
    "excludes": "没有重复状态转移、只需一次代数化简的问题。"
  },
  {
    "operator_id": "induction_structure",
    "name": "归纳结构",
    "domain": "数学证明与形式推理",
    "scope": "industry_general",
    "task_types": [
      "formal_reasoning"
    ],
    "applies_to": "命题按整数、规模、树结构或递归构造自然分层。",
    "excludes": "对象没有可递减结构，或归纳步不能覆盖所有实例。"
  },
  {
    "operator_id": "bound_sanity",
    "name": "上下界校验",
    "domain": "数学证明与形式推理",
    "scope": "industry_general",
    "task_types": [
      "formal_reasoning"
    ],
    "applies_to": "需要估计最坏情况、最好情况、复杂度或误差范围的问题。",
    "excludes": "只要求一个精确数值且不存在近似或规模变化。"
  },
  {
    "operator_id": "constructive_existence",
    "name": "构造性存在",
    "domain": "数学证明与形式推理",
    "scope": "industry_general",
    "task_types": [
      "formal_reasoning"
    ],
    "applies_to": "需要证明某对象存在，并希望给出可生成或可验证的构造。",
    "excludes": "只要求证明不存在，或已给定唯一对象。"
  },
  {
    "operator_id": "equivalence_transform",
    "name": "等价变换",
    "domain": "数学证明与形式推理",
    "scope": "industry_general",
    "task_types": [
      "formal_reasoning"
    ],
    "applies_to": "原命题直接处理困难，但可能转换为图、代数式、几何对象或优化问题。",
    "excludes": "转换会丢失方向、边界或解的一一对应关系的问题。"
  },
  {
    "operator_id": "proof_gap_audit",
    "name": "证明缺口审计",
    "domain": "数学证明与形式推理",
    "scope": "industry_general",
    "task_types": [
      "formal_reasoning"
    ],
    "applies_to": "已有证明、推导或形式化论证需要复核。",
    "excludes": "尚未提出任何可检查论证的开放式构思。"
  }
];

export const domainOperators = [
  {
    "operator_id": "value_recipient_map",
    "family": "商业模式与战略突围",
    "name": "价值与付费者对齐",
    "scope": "industry_general",
    "task_types": [
      "industry_reasoning"
    ],
    "applies_to": "任何需要明确谁使用、谁受益、谁付费的业务问题。",
    "excludes": "已经给定唯一付款方、且只讨论内部执行细节的任务。",
    "prompt": "适用：任何需要明确谁使用、谁受益、谁付费的业务问题。\n不适用：已经给定唯一付款方、且只讨论内部执行细节的任务。\n操作：先分别写出使用者、受益者、决策者和付款者，再检查四者是否为同一主体；若不是，指出价值证明要送达谁、成本由谁承担、谁能否决交易；最后只调整错位最严重的一环，并说明调整后各方为什么愿意继续参与。\n表达：使用客户实际动作和交易条件，不把“生态”“协同”当作解释。",
    "enabled": true
  },
  {
    "operator_id": "willingness_to_pay",
    "family": "商业模式与战略突围",
    "name": "支付意愿证据",
    "scope": "industry_general",
    "task_types": [
      "industry_reasoning"
    ],
    "applies_to": "定价、收费方式、免费转付费或商业化可行性问题。",
    "excludes": "公益目标或明确不要求收入回收的项目。",
    "prompt": "适用：定价、收费方式、免费转付费或商业化可行性问题。\n不适用：公益目标或明确不要求收入回收的项目。\n操作：先写出客户当前为解决同一问题付出的金钱、时间、风险或人力，再区分口头兴趣与已经发生的付费行为；然后提出最小收费测试，说明价格、承诺和退出条件；最后列出什么结果能证明客户只是喜欢而不愿付费。\n表达：优先使用订单、续费、替代成本等可观察证据。",
    "enabled": true
  },
  {
    "operator_id": "unit_economics_boundary",
    "family": "商业模式与战略突围",
    "name": "单位经济边界",
    "scope": "industry_general",
    "task_types": [
      "industry_reasoning"
    ],
    "applies_to": "规模增长、获客、履约成本和毛利是否可持续的问题。",
    "excludes": "尚未确定基本交付物、无法定义一次交易或一次服务的探索。",
    "prompt": "适用：规模增长、获客、履约成本和毛利是否可持续的问题。\n不适用：尚未确定基本交付物、无法定义一次交易或一次服务的探索。\n操作：先选定一个最小交付单位，列出获得它、交付它和售后它的边际收入与边际成本；再检查规模扩大时哪些成本下降、哪些反而上升；最后找到一条会使增长越快亏得越多的边界，并给出停止扩张或改模型的触发值。\n表达：不用“规模效应”代替实际成本项。",
    "enabled": true
  },
  {
    "operator_id": "acquisition_retention_split",
    "family": "商业模式与战略突围",
    "name": "获客与留存分离",
    "scope": "industry_general",
    "task_types": [
      "industry_reasoning"
    ],
    "applies_to": "用户增长、渠道效率、复购或使用频率问题。",
    "excludes": "一次性交付且没有复购、续期或持续使用目标的业务。",
    "prompt": "适用：用户增长、渠道效率、复购或使用频率问题。\n不适用：一次性交付且没有复购、续期或持续使用目标的业务。\n操作：先把首次到达、首次获得价值、再次回来和长期留下拆成四步，再为每一步找一个实际流失原因；然后判断问题来自入口不足还是价值未兑现；最后只针对主要断点设计验证，避免用更多流量掩盖留存问题。\n表达：说清用户在哪一步离开，不笼统说“增长乏力”。",
    "enabled": true
  },
  {
    "operator_id": "switching_friction",
    "family": "商业模式与战略突围",
    "name": "真实切换成本",
    "scope": "industry_general",
    "task_types": [
      "industry_reasoning"
    ],
    "applies_to": "竞争替代、客户迁移、产品换代和存量市场进入问题。",
    "excludes": "用户没有现有替代方案、也没有既有流程可迁移的全新需求。",
    "prompt": "适用：竞争替代、客户迁移、产品换代和存量市场进入问题。\n不适用：用户没有现有替代方案、也没有既有流程可迁移的全新需求。\n操作：先记录客户今天不用你的方案时如何完成任务，再列出迁移涉及的数据、学习、合同、关系和失败风险；然后区分可消除的麻烦与客户不愿放弃的既得利益；最后选择一个最小迁移入口，让客户无需一次性改完全部流程即可比较价值。\n表达：不要把功能更多等同于更容易替换旧方案。",
    "enabled": true
  },
  {
    "operator_id": "incentive_compatibility",
    "family": "商业模式与战略突围",
    "name": "交易激励一致性",
    "scope": "industry_general",
    "task_types": [
      "industry_reasoning"
    ],
    "applies_to": "平台、多方合作、代理销售、供应链或任何参与方行为会影响结果的业务。",
    "excludes": "单一主体能够独立完成且不存在委托关系的内部任务。",
    "prompt": "适用：平台、多方合作、代理销售、供应链或任何参与方行为会影响结果的业务。\n不适用：单一主体能够独立完成且不存在委托关系的内部任务。\n操作：先写出每一方实际因什么动作获得收益或免除责任，再对照业务希望他们做的动作；找到奖励与目标分叉的位置后，推演理性参与者会怎样钻空子；最后调整结算依据、责任范围或信息公开方式，使正确行为也是对当事人划算的行为。\n表达：用具体动作描述激励，不用“加强协同”。",
    "enabled": true
  },
  {
    "operator_id": "bottleneck_before_scale",
    "family": "商业模式与战略突围",
    "name": "扩张前瓶颈",
    "scope": "industry_general",
    "task_types": [
      "industry_reasoning"
    ],
    "applies_to": "计划扩大用户、区域、产能、团队或产品线的问题。",
    "excludes": "当前任务只是验证是否有人需要产品，尚未进入扩张讨论。",
    "prompt": "适用：计划扩大用户、区域、产能、团队或产品线的问题。\n不适用：当前任务只是验证是否有人需要产品，尚未进入扩张讨论。\n操作：先画出需求进入到价值交付的完整链路，再标出吞吐最低、等待最长或失败后返工最多的一步；然后模拟业务量增加两倍时故障会先出现在哪里；最后优先改造该瓶颈，并说明其他环节为什么暂时不值得扩容。\n表达：以排队、时延、返工率或负责人负荷说明瓶颈。",
    "enabled": true
  },
  {
    "operator_id": "reversible_business_test",
    "family": "商业模式与战略突围",
    "name": "可逆商业试验",
    "scope": "industry_general",
    "task_types": [
      "industry_reasoning"
    ],
    "applies_to": "高不确定的新市场、新定价、新客群或合作方式选择。",
    "excludes": "已经涉及不可逆监管承诺、安全风险或大额长期合同的决定。",
    "prompt": "适用：高不确定的新市场、新定价、新客群或合作方式选择。\n不适用：已经涉及不可逆监管承诺、安全风险或大额长期合同的决定。\n操作：先写出最关键且尚未证实的商业假设，再设计一个限定客群、期限和损失上限的小实验；明确继续、修改和停止的判据后再投入；最后检查实验结果是否真的能区分两个相反判断，而不是无论结果如何都能解释为成功。\n表达：把学习目标写在投入方案之前。",
    "enabled": true
  },
  {
    "operator_id": "flow_load_curve",
    "family": "游戏机制与系统规则设计",
    "name": "心流负荷曲线",
    "scope": "industry_general",
    "task_types": [
      "industry_reasoning"
    ],
    "applies_to": "任何需要安排挑战强度、学习节奏和持续投入感的游戏。",
    "excludes": "没有玩家操作、选择或理解过程的纯展示内容。",
    "prompt": "适用：任何需要安排挑战强度、学习节奏和持续投入感的游戏。\n不适用：没有玩家操作、选择或理解过程的纯展示内容。\n操作：先按实际游玩时间画出玩家能力、任务难度和同时需要处理的信息量，再标出明显无聊、困惑或焦虑的区段；然后只改变目标粒度、提示时机、容错或节奏中的一项；最后用停顿、重复误操作、跳过和退出位置验证负荷是否回到玩家可掌握但仍需投入的范围。\n表达：描述玩家此刻要看什么、想什么、做什么，不把“心流”本身当成答案。",
    "enabled": true
  },
  {
    "operator_id": "meaningful_choice_density",
    "family": "游戏机制与系统规则设计",
    "name": "有效选择密度",
    "scope": "industry_general",
    "task_types": [
      "industry_reasoning"
    ],
    "applies_to": "任何强调玩家选择、资源分配或重复游玩的游戏。",
    "excludes": "设计目标明确是短时放松、且主要价值来自无决策的感官反馈时。",
    "prompt": "适用：任何强调玩家选择、资源分配或重复游玩的游戏。\n不适用：设计目标明确是短时放松、且主要价值来自无决策的感官反馈时。\n操作：先列出一段游玩中所有可选动作，再逐个检查不同选择是否会改变后续状态、资源、信息或目标；删除只有表现差异的伪选择后，计算真正选择之间的等待时间；最后调整选择频率和后果持续时间，使玩家既不会连续空转，也有时间理解上一次决定。\n表达：用“选择后哪件事变了”判断意义，不以按钮数量判断。",
    "enabled": true
  },
  {
    "operator_id": "feedback_traceability",
    "family": "游戏机制与系统规则设计",
    "name": "反馈可归因性",
    "scope": "industry_general",
    "task_types": [
      "industry_reasoning"
    ],
    "applies_to": "任何玩家行动会产生数值、状态、进度或叙事结果的游戏。",
    "excludes": "结果刻意不可知且不可推理就是核心体验的局部段落。",
    "prompt": "适用：任何玩家行动会产生数值、状态、进度或叙事结果的游戏。\n不适用：结果刻意不可知且不可推理就是核心体验的局部段落。\n操作：先选一个关键结果，倒查玩家能否看见它由哪次选择、哪条规则和哪个条件造成；再检查反馈是否过晚、同时出现太多结果或被无关表现遮住；最后让玩家无需查外部资料也能复述“我做了什么，所以发生了什么”，同时保留必要的不确定性。\n表达：先说因果链，再讨论动画、音效或界面包装。",
    "enabled": true
  },
  {
    "operator_id": "visible_compounding",
    "family": "游戏机制与系统规则设计",
    "name": "复利快感检验",
    "scope": "industry_general",
    "task_types": [
      "industry_reasoning"
    ],
    "applies_to": "成长、经营、收集、解谜效率或任何允许玩家建立长期增益的游戏。",
    "excludes": "追求固定能力、每局完全重置且不希望效率加速的体验。",
    "prompt": "适用：成长、经营、收集、解谜效率或任何允许玩家建立长期增益的游戏。\n不适用：追求固定能力、每局完全重置且不希望效率加速的体验。\n操作：先找出玩家反复执行的基础行为和由其主动搭建的增益来源，再比较增益前后同样投入带来的可见结果；然后检查玩家能否把提升归因于自己的构筑，而不是系统自动送出的倍率；最后确认加速会打开新选择或新用途，而不只是更快耗尽剩余内容。\n表达：用一次具体操作前后的差别说明复利，不创造新的能量或物理学名词。",
    "enabled": true
  },
  {
    "operator_id": "progression_runway",
    "family": "游戏机制与系统规则设计",
    "name": "成长跑道检查",
    "scope": "industry_general",
    "task_types": [
      "industry_reasoning"
    ],
    "applies_to": "存在长期属性、关卡、能力、资源或内容解锁进度的游戏。",
    "excludes": "单次体验很短且没有持续成长目标的作品。",
    "prompt": "适用：存在长期属性、关卡、能力、资源或内容解锁进度的游戏。\n不适用：单次体验很短且没有持续成长目标的作品。\n操作：先估算普通玩家、熟练玩家和极端优化玩家消耗主要成长空间所需的实际游玩次数；再标出封顶后仍值得做的事情以及它们是否产生新决策；最后调整成长对象、阶段目标或收益出口，保证效率提升不会提前消灭后半程目标，也不靠隐藏削弱让增益失去体感。\n表达：给出至少一条真实推进曲线或回合示例。",
    "enabled": true
  },
  {
    "operator_id": "dominant_strategy_check",
    "family": "游戏机制与系统规则设计",
    "name": "支配策略检查",
    "scope": "industry_general",
    "task_types": [
      "industry_reasoning"
    ],
    "applies_to": "任何提供两个以上可重复选择、组合或发展方向的游戏。",
    "excludes": "明确设计为只有一种解法的教学步骤或短篇固定流程。",
    "prompt": "适用：任何提供两个以上可重复选择、组合或发展方向的游戏。\n不适用：明确设计为只有一种解法的教学步骤或短篇固定流程。\n操作：先找出在多数局面下都更安全、更快或收益更高的选择，再说明玩家为什么没有理由改用其他选择；然后分别检查信息不足、成本过低、风险可忽略或收益覆盖面过广哪一项造成支配；最后修改根因并验证其他选择是在不同条件下更好，而不是统一加减几个百分点。\n表达：讨论适用局面和机会成本，不使用“强制平衡”作为解释。",
    "enabled": true
  },
  {
    "operator_id": "failure_recovery",
    "family": "游戏机制与系统规则设计",
    "name": "失败与恢复路径",
    "scope": "industry_general",
    "task_types": [
      "industry_reasoning"
    ],
    "applies_to": "任何允许犯错、损失资源、卡住或未达成目标的游戏。",
    "excludes": "失败即结束且一次尝试本身极短、重新开始没有成本的局部挑战。",
    "prompt": "适用：任何允许犯错、损失资源、卡住或未达成目标的游戏。\n不适用：失败即结束且一次尝试本身极短、重新开始没有成本的局部挑战。\n操作：先记录玩家失败后保留了什么信息、进度和重新选择的空间，再判断失败是在教规则还是只重复消耗时间；然后设计最小恢复路径，使玩家能够根据刚获得的信息改变下一次行动；最后确认恢复不会抹平此前选择的后果，也不会让一次早期错误毁掉全部后续体验。\n表达：用玩家失败后的下一分钟说明恢复是否有效。",
    "enabled": true
  },
  {
    "operator_id": "returnability",
    "family": "游戏机制与系统规则设计",
    "name": "中断后回归",
    "scope": "industry_general",
    "task_types": [
      "industry_reasoning"
    ],
    "applies_to": "可能跨天游玩、单局较长、系统较多或允许长期积累的游戏。",
    "excludes": "数分钟内一次完成且不会保存状态的体验。",
    "prompt": "适用：可能跨天游玩、单局较长、系统较多或允许长期积累的游戏。\n不适用：数分钟内一次完成且不会保存状态的体验。\n操作：先假设玩家离开一周后回来，检查他能否看懂当前目标、已有资源、上次决定及最近风险；再找出必须靠记忆才能继续的隐性信息；最后用状态摘要、可回看因果或低风险热身让玩家恢复判断，但不替玩家自动做关键选择。\n表达：以“回来后第一步知道做什么”为验收标准。",
    "enabled": true
  },
  {
    "operator_id": "character_goal_pressure",
    "family": "剧作编剧与长篇内容叙事",
    "name": "角色目标与压力",
    "scope": "industry_general",
    "task_types": [
      "industry_reasoning"
    ],
    "applies_to": "由人物行动推动的影视、小说、互动叙事和长篇内容。",
    "excludes": "没有人物主体、只做事实说明的内容。",
    "prompt": "适用：由人物行动推动的影视、小说、互动叙事和长篇内容。\n不适用：没有人物主体、只做事实说明的内容。\n操作：先写清角色此刻具体想得到什么、为什么现在必须行动、失败会失去什么；再检查阻力是否迫使角色作出暴露价值取向的选择；最后删除只让事情变麻烦却不改变决定的障碍，保留能使角色付出代价的压力。\n表达：用可观察的行动说明欲望，不只写性格形容词。",
    "enabled": true
  },
  {
    "operator_id": "causal_story_chain",
    "family": "剧作编剧与长篇内容叙事",
    "name": "叙事因果链",
    "scope": "industry_general",
    "task_types": [
      "industry_reasoning"
    ],
    "applies_to": "任何要求事件前后具有可信联系的叙事。",
    "excludes": "明确以碎片联想、梦境或无因果并置为主要形式的实验作品。",
    "prompt": "适用：任何要求事件前后具有可信联系的叙事。\n不适用：明确以碎片联想、梦境或无因果并置为主要形式的实验作品。\n操作：先把关键事件改写成“因为前一件事，所以角色做了下一件事”；若只能用“然后”连接，就找出缺失的动机、信息或现实条件；补齐后再检查结果是否反过来改变角色后续选择；最后指出链条中最依赖巧合的一步。\n表达：区分作者需要发生与角色有理由去做。",
    "enabled": true
  },
  {
    "operator_id": "information_release",
    "family": "剧作编剧与长篇内容叙事",
    "name": "信息释放顺序",
    "scope": "industry_general",
    "task_types": [
      "industry_reasoning"
    ],
    "applies_to": "悬念、理解、发现过程会影响体验的叙事。",
    "excludes": "信息顺序不影响理解的工具性说明。",
    "prompt": "适用：悬念、理解、发现过程会影响体验的叙事。\n不适用：信息顺序不影响理解的工具性说明。\n操作：先列出受众、角色和作者在每个关键节点分别知道什么，再检查过早透露会消灭什么期待、过晚透露会造成什么误解；然后调整一个信息的出现时机；最后验证受众当时能够提出正确的问题，但还不知道答案。\n表达：不把故意隐瞒必要信息冒充悬念。",
    "enabled": true
  },
  {
    "operator_id": "viewpoint_knowledge",
    "family": "剧作编剧与长篇内容叙事",
    "name": "视角与可知范围",
    "scope": "industry_general",
    "task_types": [
      "industry_reasoning"
    ],
    "applies_to": "需要选择叙述视角、切换人物或控制信息可信度的内容。",
    "excludes": "完全客观、无人物视角的简短记录。",
    "prompt": "适用：需要选择叙述视角、切换人物或控制信息可信度的内容。\n不适用：完全客观、无人物视角的简短记录。\n操作：先确定当前段落由谁感知以及他不可能知道什么，再检查文字是否越过该视角偷渡解释；然后比较换成另一视角会增加什么、损失什么；最后只在改变理解或情绪距离时切换视角。\n表达：视角选择必须改变信息或感受，不能只是换称谓。",
    "enabled": true
  },
  {
    "operator_id": "tension_variation",
    "family": "剧作编剧与长篇内容叙事",
    "name": "张力变化",
    "scope": "industry_general",
    "task_types": [
      "industry_reasoning"
    ],
    "applies_to": "需要维持阅读、观看或游玩投入的中长篇叙事。",
    "excludes": "只有单一信息点的极短内容。",
    "prompt": "适用：需要维持阅读、观看或游玩投入的中长篇叙事。\n不适用：只有单一信息点的极短内容。\n操作：先沿时间标出期待、风险、未知和喘息的变化，再找出长时间没有新问题、没有决定或持续同一强度的平段；然后通过改变目标、时限或关系压力制造层次；最后确认安静段也在积累理解，而不是纯粹停滞。\n表达：张力不是持续提高音量或灾难规模。",
    "enabled": true
  },
  {
    "operator_id": "setup_payoff",
    "family": "剧作编剧与长篇内容叙事",
    "name": "伏笔与兑现",
    "scope": "industry_general",
    "task_types": [
      "industry_reasoning"
    ],
    "applies_to": "需要回收前文信息、承诺或情绪期待的叙事。",
    "excludes": "刻意拒绝闭合、且这种未完成感就是主题的作品。",
    "prompt": "适用：需要回收前文信息、承诺或情绪期待的叙事。\n不适用：刻意拒绝闭合、且这种未完成感就是主题的作品。\n操作：先列出前文让受众记住并期待后续意义的细节，再标记每项是否改变了理解、选择或结果；对没有兑现的细节决定删除、弱化或补回收；最后检查兑现既能回看成立，又不是靠临时新增规则完成。\n表达：伏笔的价值在后果，不在隐晦程度。",
    "enabled": true
  },
  {
    "operator_id": "character_consistency",
    "family": "剧作编剧与长篇内容叙事",
    "name": "人物一致与变化",
    "scope": "industry_general",
    "task_types": [
      "industry_reasoning"
    ],
    "applies_to": "人物需要在较长时间内保持可信并发生变化的叙事。",
    "excludes": "人物只是无人格的信息载体。",
    "prompt": "适用：人物需要在较长时间内保持可信并发生变化的叙事。\n不适用：人物只是无人格的信息载体。\n操作：先写出角色面对压力时稳定保留的判断方式，再找到故事中足以改变它的连续经历；然后检查转变前是否已有可观察的松动、转变后是否体现在选择而非自白；最后指出如果删去哪段经历，人物变化就不再可信。\n表达：一致不等于永远做同一件事，变化也不能只靠一句顿悟。",
    "enabled": true
  },
  {
    "operator_id": "audience_orientation",
    "family": "剧作编剧与长篇内容叙事",
    "name": "受众理解定位",
    "scope": "industry_general",
    "task_types": [
      "industry_reasoning"
    ],
    "applies_to": "人物、时间线、规则或背景较复杂的叙事。",
    "excludes": "复杂和迷失本身是经过验证的核心体验时。",
    "prompt": "适用：人物、时间线、规则或背景较复杂的叙事。\n不适用：复杂和迷失本身是经过验证的核心体验时。\n操作：先在每个段落回答受众是否知道自己在哪里、跟随谁、当前目标是什么；再区分有意保留的未知与无意造成的混乱；最后用最少的重复、视觉锚点或行动目标恢复定位，并检查补充信息是否打断叙事推进。\n表达：不要用旁白一次解释全部背景来掩盖组织问题。",
    "enabled": true
  },
  {
    "operator_id": "real_use_context",
    "family": "实体产品、硬件与交互设计",
    "name": "真实使用情境",
    "scope": "industry_general",
    "task_types": [
      "industry_reasoning"
    ],
    "applies_to": "任何需要人在现实环境中拿取、安装、操作或维护的产品。",
    "excludes": "完全没有实体接触和环境约束的纯软件任务。",
    "prompt": "适用：任何需要人在现实环境中拿取、安装、操作或维护的产品。\n不适用：完全没有实体接触和环境约束的纯软件任务。\n操作：先描述目标用户在真实地点、姿势、光线、噪声、手部占用和时间压力下完成任务的过程，再找出实验室条件掩盖的困难；然后只改动最妨碍任务完成的接触点；最后在最差但常见的使用条件下复测。\n表达：用动作和环境变量说明问题，不用抽象的“体验升级”。",
    "enabled": true
  },
  {
    "operator_id": "affordance_clarity",
    "family": "实体产品、硬件与交互设计",
    "name": "操作示意清晰度",
    "scope": "industry_general",
    "task_types": [
      "industry_reasoning"
    ],
    "applies_to": "存在按钮、把手、接口、开合、插拔、方向或状态切换的产品。",
    "excludes": "用户不会直接操作、只由专业设备自动执行的内部部件。",
    "prompt": "适用：存在按钮、把手、接口、开合、插拔、方向或状态切换的产品。\n不适用：用户不会直接操作、只由专业设备自动执行的内部部件。\n操作：先让不了解产品的人在没有说明书时判断哪里能操作、朝哪个方向、操作后是否成功；再记录误触和犹豫来自形状、位置、阻力还是反馈；最后优先用外形和触感表达正确动作，把文字说明留给无法自然表达的信息。\n表达：明确用户看到和摸到的线索。",
    "enabled": true
  },
  {
    "operator_id": "load_path",
    "family": "实体产品、硬件与交互设计",
    "name": "受力与传递路径",
    "scope": "industry_general",
    "task_types": [
      "industry_reasoning"
    ],
    "applies_to": "承受重量、冲击、振动、热量、压力或反复动作的实体设计。",
    "excludes": "没有显著物理载荷的外观讨论。",
    "prompt": "适用：承受重量、冲击、振动、热量、压力或反复动作的实体设计。\n不适用：没有显著物理载荷的外观讨论。\n操作：先从输入位置画出力、热或振动经过哪些零件传到哪里，再找出截面突变、连接松动、热积累和材料不匹配的位置；然后检查正常、误用和跌落情境；最后把保护放在载荷真正经过的路径上，而不是只增加整体材料。\n表达：说明输入、路径和失效点，不笼统说“加强结构”。",
    "enabled": true
  },
  {
    "operator_id": "tolerance_stack",
    "family": "实体产品、硬件与交互设计",
    "name": "公差累积",
    "scope": "industry_general",
    "task_types": [
      "industry_reasoning"
    ],
    "applies_to": "多个零件装配、运动配合、密封、定位或批量生产问题。",
    "excludes": "单件手工原型且暂不要求重复制造的探索。",
    "prompt": "适用：多个零件装配、运动配合、密封、定位或批量生产问题。\n不适用：单件手工原型且暂不要求重复制造的探索。\n操作：先列出决定关键间隙或位置的全部尺寸，再按最坏方向叠加制造、装配、温度和磨损偏差；然后判断卡死、松脱或泄漏最先出现在哪里；最后把精度预算集中到真正影响功能的尺寸，并为其他尺寸留下可制造余量。\n表达：给出关键尺寸链和可接受范围。",
    "enabled": true
  },
  {
    "operator_id": "safe_failure",
    "family": "实体产品、硬件与交互设计",
    "name": "安全失效",
    "scope": "industry_general",
    "task_types": [
      "industry_reasoning"
    ],
    "applies_to": "故障可能伤人、损坏周边、丢失关键数据或阻断基本功能的产品。",
    "excludes": "失败后没有实质损失、可以立即重试的一次性模型。",
    "prompt": "适用：故障可能伤人、损坏周边、丢失关键数据或阻断基本功能的产品。\n不适用：失败后没有实质损失、可以立即重试的一次性模型。\n操作：先列出最可能和后果最严重的故障，再写出故障发生后产品会停下、继续、误导还是突然释放能量；然后让单点故障优先进入可见、可停、可恢复的状态；最后验证保护本身失效时是否会制造更危险的结果。\n表达：区分故障概率与故障后果。",
    "enabled": true
  },
  {
    "operator_id": "maintenance_access",
    "family": "实体产品、硬件与交互设计",
    "name": "维护可达性",
    "scope": "industry_general",
    "task_types": [
      "industry_reasoning"
    ],
    "applies_to": "需要清洁、更换耗材、校准、维修或长期使用的产品。",
    "excludes": "使用寿命很短且按计划整体更换的低风险物品。",
    "prompt": "适用：需要清洁、更换耗材、校准、维修或长期使用的产品。\n不适用：使用寿命很短且按计划整体更换的低风险物品。\n操作：先按发生频率列出维护任务，再记录完成每项任务需要拆多少部件、使用什么工具、是否可能装错；然后让最高频或最关键的任务最容易到达；最后检查维护完成后是否有明确的恢复确认，避免设备看似装好却处于错误状态。\n表达：用分钟、步骤和工具数量说明维护成本。",
    "enabled": true
  },
  {
    "operator_id": "lifecycle_tradeoff",
    "family": "实体产品、硬件与交互设计",
    "name": "生命周期取舍",
    "scope": "industry_general",
    "task_types": [
      "industry_reasoning"
    ],
    "applies_to": "材料、能耗、耐久、成本、可修复性和回收之间需要权衡的产品。",
    "excludes": "只验证短期功能、尚未进入材料和量产决策的概念模型。",
    "prompt": "适用：材料、能耗、耐久、成本、可修复性和回收之间需要权衡的产品。\n不适用：只验证短期功能、尚未进入材料和量产决策的概念模型。\n操作：先确定产品从制造、运输、使用、维护到报废的主要成本和影响，再检查某个阶段的优化是否把负担转移到另一个阶段；然后选择与实际使用寿命匹配的设计；最后说明用户、制造方和环境分别承担了什么代价。\n表达：不要只用单一材料标签判断可持续性。",
    "enabled": true
  },
  {
    "operator_id": "measurable_prototype",
    "family": "实体产品、硬件与交互设计",
    "name": "可测量原型",
    "scope": "industry_general",
    "task_types": [
      "industry_reasoning"
    ],
    "applies_to": "硬件概念尚未验证、存在关键人体或物理假设的设计。",
    "excludes": "已经有稳定量产数据、当前只处理明确缺陷的任务。",
    "prompt": "适用：硬件概念尚未验证、存在关键人体或物理假设的设计。\n不适用：已经有稳定量产数据、当前只处理明确缺陷的任务。\n操作：先找出一个失败就足以否定方案的关键假设，再制作只包含验证该假设所需结构的最低成本原型；提前写下测量方法和通过阈值；最后在接近真实使用的条件下测试，避免用外观完整度代替功能证据。\n表达：先说要学到什么，再说要做什么原型。",
    "enabled": true
  },
  {
    "operator_id": "decision_rights",
    "family": "组织机制与治理博弈",
    "name": "决策权边界",
    "scope": "industry_general",
    "task_types": [
      "industry_reasoning"
    ],
    "applies_to": "多人协作中出现等待、越权、重复审批或无人拍板的问题。",
    "excludes": "单人能够独立决定并执行的任务。",
    "prompt": "适用：多人协作中出现等待、越权、重复审批或无人拍板的问题。\n不适用：单人能够独立决定并执行的任务。\n操作：先列出关键决定及其提出者、提供信息者、最终决定者和执行者，再找出多人都能否决或无人真正负责的环节；然后把决定权交给最接近必要信息且承担结果的人；最后明确哪些条件必须升级处理。\n表达：按具体决定分权，不按职位名称笼统分权。",
    "enabled": true
  },
  {
    "operator_id": "incentive_behavior",
    "family": "组织机制与治理博弈",
    "name": "激励与实际行为",
    "scope": "industry_general",
    "task_types": [
      "industry_reasoning"
    ],
    "applies_to": "考核、奖金、晋升、配额或声誉影响成员行为的组织。",
    "excludes": "没有持续参与者、也不存在评价和资源分配的短期协作。",
    "prompt": "适用：考核、奖金、晋升、配额或声誉影响成员行为的组织。\n不适用：没有持续参与者、也不存在评价和资源分配的短期协作。\n操作：先写出组织口头希望的行为，再写出成员实际因什么指标获得利益或避免损失；找到两者分叉的具体动作后，推演最省力的应付方式；最后调整指标、抽样或责任安排，使做对事情比做表面数字更划算。\n表达：用可观察行为判断激励，不猜测态度。",
    "enabled": true
  },
  {
    "operator_id": "information_path",
    "family": "组织机制与治理博弈",
    "name": "信息到达路径",
    "scope": "industry_general",
    "task_types": [
      "industry_reasoning"
    ],
    "applies_to": "决策质量受到层级汇报、跨部门传递或信息过滤影响的问题。",
    "excludes": "所有相关人员已经共享同一实时事实来源的简单协作。",
    "prompt": "适用：决策质量受到层级汇报、跨部门传递或信息过滤影响的问题。\n不适用：所有相关人员已经共享同一实时事实来源的简单协作。\n操作：先追踪一个坏消息或异常从现场到决策者经过哪些人、表格和会议，再记录每一步的延迟与被修改动机；然后缩短最影响行动时机的路径；最后让原始证据与解释同时可见，避免只留下经过美化的结论。\n表达：区分没有信息、信息太晚和信息不敢上报。",
    "enabled": true
  },
  {
    "operator_id": "accountability_control",
    "family": "组织机制与治理博弈",
    "name": "责任与控制能力",
    "scope": "industry_general",
    "task_types": [
      "industry_reasoning"
    ],
    "applies_to": "追责、授权、跨团队依赖和结果归属不清的问题。",
    "excludes": "结果完全由单一执行者控制的独立任务。",
    "prompt": "适用：追责、授权、跨团队依赖和结果归属不清的问题。\n不适用：结果完全由单一执行者控制的独立任务。\n操作：先写出谁对结果负责，再列出他实际能控制的预算、人员、时间和依赖；如果责任大于控制能力，指出缺失权限或外部约束；最后重新分配责任或控制权，并保留对不可控部分的明确记录。\n表达：不能让“负责”成为没有权限的背锅标签。",
    "enabled": true
  },
  {
    "operator_id": "conflict_resolution",
    "family": "组织机制与治理博弈",
    "name": "冲突处理路径",
    "scope": "industry_general",
    "task_types": [
      "industry_reasoning"
    ],
    "applies_to": "不同目标、专业判断或资源需求会反复冲突的组织。",
    "excludes": "一次性的人际争执且不涉及重复协作机制。",
    "prompt": "适用：不同目标、专业判断或资源需求会反复冲突的组织。\n不适用：一次性的人际争执且不涉及重复协作机制。\n操作：先区分事实分歧、目标分歧和资源分歧，再为每类分歧确定所需证据和裁决者；然后规定到什么时间必须做出可暂时执行的决定；最后保存异议和复查条件，使冲突不会无限拖延，也不会被权力直接抹掉。\n表达：先判断冲突类型，再选择处理方式。",
    "enabled": true
  },
  {
    "operator_id": "exception_handling",
    "family": "组织机制与治理博弈",
    "name": "例外处理",
    "scope": "industry_general",
    "task_types": [
      "industry_reasoning"
    ],
    "applies_to": "规则经常被临时绕过、特殊审批越来越多的组织。",
    "excludes": "尚无稳定流程、所有情况都仍在探索期的团队。",
    "prompt": "适用：规则经常被临时绕过、特殊审批越来越多的组织。\n不适用：尚无稳定流程、所有情况都仍在探索期的团队。\n操作：先记录最近发生的例外、提出理由和实际后果，再区分规则本身错误、信息不完整和真正罕见情况；然后为必要例外设置期限、责任人和复查；最后统计重复例外，重复出现时修改规则而不是继续人工放行。\n表达：例外必须留下原因和失效日期。",
    "enabled": true
  },
  {
    "operator_id": "feedback_cadence",
    "family": "组织机制与治理博弈",
    "name": "反馈周期匹配",
    "scope": "industry_general",
    "task_types": [
      "industry_reasoning"
    ],
    "applies_to": "目标周期、复盘频率和实际变化速度不一致的问题。",
    "excludes": "结果即时可见、无需跨周期调整的简单任务。",
    "prompt": "适用：目标周期、复盘频率和实际变化速度不一致的问题。\n不适用：结果即时可见、无需跨周期调整的简单任务。\n操作：先确定行为到结果之间通常隔多久，再检查组织是在结果还没出现前频繁改方向，还是在问题积累很久后才发现；然后让过程信号、结果指标和战略复盘使用不同周期；最后验证每次反馈都能影响下一次仍可改变的决定。\n表达：反馈频率由因果延迟决定，不由会议习惯决定。",
    "enabled": true
  },
  {
    "operator_id": "reversible_governance",
    "family": "组织机制与治理博弈",
    "name": "可逆治理试点",
    "scope": "industry_general",
    "task_types": [
      "industry_reasoning"
    ],
    "applies_to": "组织制度调整影响较大、但真实后果尚不确定的情况。",
    "excludes": "涉及法定责任、安全红线或不可逆人员伤害的决定。",
    "prompt": "适用：组织制度调整影响较大、但真实后果尚不确定的情况。\n不适用：涉及法定责任、安全红线或不可逆人员伤害的决定。\n操作：先明确新制度想解决的单一问题，再限定试点范围、期限和退出方式；提前定义对员工和业务都可观察的成功与伤害指标；最后在扩大前检查改善是否来自制度本身，而不是试点获得了额外关注或资源。\n表达：把试点当成学习，不把临时成功包装成永久正确。",
    "enabled": true
  },
  {
    "operator_id": "requirement_partition",
    "family": "技术架构与底层算法攻关",
    "name": "需求分层",
    "scope": "industry_general",
    "task_types": [
      "industry_reasoning"
    ],
    "applies_to": "技术方案同时包含性能、一致性、成本、安全或可用性目标的问题。",
    "excludes": "需求已经单一明确、只需修复局部实现错误的任务。",
    "prompt": "适用：技术方案同时包含性能、一致性、成本、安全或可用性目标的问题。\n不适用：需求已经单一明确、只需修复局部实现错误的任务。\n操作：先把需求分成绝不能违反的底线、目标值和可协商偏好，再为每项写出业务后果和测量方法；然后找出彼此冲突的要求；最后要求方案明确牺牲了什么，避免用“高性能高可用强一致”代替取舍。\n表达：每项要求必须能够测量或通过故障情境验证。",
    "enabled": true
  },
  {
    "operator_id": "latency_budget",
    "family": "技术架构与底层算法攻关",
    "name": "时延预算",
    "scope": "industry_general",
    "task_types": [
      "industry_reasoning"
    ],
    "applies_to": "用户请求、数据处理或跨服务链路存在响应时间目标的系统。",
    "excludes": "离线批处理且完成时间没有业务约束的任务。",
    "prompt": "适用：用户请求、数据处理或跨服务链路存在响应时间目标的系统。\n不适用：离线批处理且完成时间没有业务约束的任务。\n操作：先从端到端目标反推网络、排队、计算、存储和重试各自能占多少时间，再用当前观测值找出最大和波动最大的部分；然后优先处理超预算环节；最后检查优化是否把延迟转移到一致性、失败恢复或后台积压。\n表达：使用分位数和端到端时间，不只看平均值。",
    "enabled": true
  },
  {
    "operator_id": "state_ownership",
    "family": "技术架构与底层算法攻关",
    "name": "状态归属",
    "scope": "industry_general",
    "task_types": [
      "industry_reasoning"
    ],
    "applies_to": "多个服务、节点或区域都可能读取和修改同一业务状态的问题。",
    "excludes": "无持久状态的纯计算任务。",
    "prompt": "适用：多个服务、节点或区域都可能读取和修改同一业务状态的问题。\n不适用：无持久状态的纯计算任务。\n操作：先为每类状态写出唯一事实来源、允许写入者和冲突判定依据，再列出断网、重复请求和乱序到达时可能出现的多个版本；然后选择谁能在什么范围内独立决定；最后说明合并失败时用户会看到什么以及如何恢复。\n表达：先定义状态和所有权，再讨论同步技术。",
    "enabled": true
  },
  {
    "operator_id": "failure_domain",
    "family": "技术架构与底层算法攻关",
    "name": "故障域",
    "scope": "industry_general",
    "task_types": [
      "industry_reasoning"
    ],
    "applies_to": "分布式、依赖外部服务或要求持续可用的系统。",
    "excludes": "故障后可以整体重启且没有数据或时间损失的本地工具。",
    "prompt": "适用：分布式、依赖外部服务或要求持续可用的系统。\n不适用：故障后可以整体重启且没有数据或时间损失的本地工具。\n操作：先列出进程、机器、机房、网络、依赖和人为配置可能分别失效，再标出一次故障会同时影响哪些组件；然后缩小最关键的共同故障域；最后验证隔离后的系统不会因为共享凭据、控制面或发布流程再次一起失败。\n表达：用具体故障情境说明隔离，不以副本数量代替分析。",
    "enabled": true
  },
  {
    "operator_id": "consistency_semantics",
    "family": "技术架构与底层算法攻关",
    "name": "一致性语义",
    "scope": "industry_general",
    "task_types": [
      "industry_reasoning"
    ],
    "applies_to": "数据可能并发修改、延迟复制或被多个位置观察的系统。",
    "excludes": "只追加且读取顺序完全不影响业务结果的独立日志。",
    "prompt": "适用：数据可能并发修改、延迟复制或被多个位置观察的系统。\n不适用：只追加且读取顺序完全不影响业务结果的独立日志。\n操作：先让业务方说明哪些冲突绝不能出现、哪些短暂旧值可以接受、多久后必须一致；再为创建、更新、删除和重复提交分别定义行为；然后用两个并发用户和一次网络中断推演结果；最后才选择满足这些语义的实现方式。\n表达：使用用户可见结果定义一致性，不先抛协议名称。",
    "enabled": true
  },
  {
    "operator_id": "capacity_backlog",
    "family": "技术架构与底层算法攻关",
    "name": "容量与积压",
    "scope": "industry_general",
    "task_types": [
      "industry_reasoning"
    ],
    "applies_to": "有队列、异步处理、突发流量或上下游速率差的系统。",
    "excludes": "请求量固定且所有工作同步完成的简单工具。",
    "prompt": "适用：有队列、异步处理、突发流量或上下游速率差的系统。\n不适用：请求量固定且所有工作同步完成的简单工具。\n操作：先测量稳定输入速率、峰值、处理速率和可接受等待时间，再计算积压在最坏常见峰值下多久能清空；然后定义拒绝、降级或限速发生的阈值；最后确认保护措施不会让上游无限重试或让重要请求与低价值任务一起被淹没。\n表达：把缓存容量和恢复时间一起说明。",
    "enabled": true
  },
  {
    "operator_id": "observability_question",
    "family": "技术架构与底层算法攻关",
    "name": "可观测性问题",
    "scope": "industry_general",
    "task_types": [
      "industry_reasoning"
    ],
    "applies_to": "系统出现慢、错、丢失或偶发异常但难以定位的问题。",
    "excludes": "原因已经由可重复测试明确定位的单点缺陷。",
    "prompt": "适用：系统出现慢、错、丢失或偶发异常但难以定位的问题。\n不适用：原因已经由可重复测试明确定位的单点缺陷。\n操作：先写出事故发生时最需要回答的三个问题，再检查现有日志、指标和链路信息能否在不重放事故的情况下回答；然后补充能区分主要假设的最少信号；最后设置保留时间、关联标识和告警条件，避免收集大量无法行动的数据。\n表达：每个信号都要对应一个可采取的决定。",
    "enabled": true
  },
  {
    "operator_id": "migration_reversibility",
    "family": "技术架构与底层算法攻关",
    "name": "迁移可逆性",
    "scope": "industry_general",
    "task_types": [
      "industry_reasoning"
    ],
    "applies_to": "更换存储、协议、模型、平台或核心数据结构的系统改造。",
    "excludes": "没有存量数据和在线用户的全新系统原型。",
    "prompt": "适用：更换存储、协议、模型、平台或核心数据结构的系统改造。\n不适用：没有存量数据和在线用户的全新系统原型。\n操作：先列出迁移期间新旧系统分别读写什么，再找出不可逆的数据变换和切换点；然后设计小流量验证、结果对比和明确回退窗口；最后确认回退不会丢失迁移期间产生的新状态，也不会依赖已经停用的旧能力。\n表达：把回退步骤与正常迁移步骤同等设计。",
    "enabled": true
  },
  {
    "operator_id": "audience_job",
    "family": "品牌营销与迷因破圈",
    "name": "受众当前任务",
    "scope": "industry_general",
    "task_types": [
      "industry_reasoning"
    ],
    "applies_to": "需要确定传播对象、使用场景或信息重点的营销问题。",
    "excludes": "受众、场景和购买原因已经由可靠行为数据明确给定的执行任务。",
    "prompt": "适用：需要确定传播对象、使用场景或信息重点的营销问题。\n不适用：受众、场景和购买原因已经由可靠行为数据明确给定的执行任务。\n操作：先写出受众在接触信息的当时正在完成什么任务、担心什么、已有何种替代选择，再区分人口标签与真实处境；然后选择最影响其下一步行动的一个问题；最后让信息围绕该问题展开，而不是试图同时覆盖所有卖点。\n表达：用具体场景定义受众，不用“年轻人”“高净值”等空泛标签。",
    "enabled": true
  },
  {
    "operator_id": "promise_evidence",
    "family": "品牌营销与迷因破圈",
    "name": "承诺与证据",
    "scope": "industry_general",
    "task_types": [
      "industry_reasoning"
    ],
    "applies_to": "广告、品牌主张、销售页面和新品传播。",
    "excludes": "只传达时间、地点等无需说服的事实通知。",
    "prompt": "适用：广告、品牌主张、销售页面和新品传播。\n不适用：只传达时间、地点等无需说服的事实通知。\n操作：先把核心承诺写成受众能够验证的一句话，再列出产品、数据、演示、第三方或用户行为中的证据；然后检查证据是否直接支持承诺而不是只制造气氛；最后删掉无法证明、容易误解或超出产品能力的表述。\n表达：证据强度必须与承诺强度匹配。",
    "enabled": true
  },
  {
    "operator_id": "message_distinction",
    "family": "品牌营销与迷因破圈",
    "name": "信息区分度",
    "scope": "industry_general",
    "task_types": [
      "industry_reasoning"
    ],
    "applies_to": "同类产品表达相似、受众记不住差别的问题。",
    "excludes": "市场尚无相近替代、当前主要障碍是受众不知道品类存在。",
    "prompt": "适用：同类产品表达相似、受众记不住差别的问题。\n不适用：市场尚无相近替代、当前主要障碍是受众不知道品类存在。\n操作：先收集受众会同时看到的三到五个竞争表达，再遮住品牌名检查是否可以互换；然后找到一个真实、重要且能被证明的差异；最后用同一受众场景比较新表达是否改变选择理由，而不只追求语言新奇。\n表达：区分度来自事实和取舍，不来自生造词。",
    "enabled": true
  },
  {
    "operator_id": "channel_context",
    "family": "品牌营销与迷因破圈",
    "name": "渠道情境匹配",
    "scope": "industry_general",
    "task_types": [
      "industry_reasoning"
    ],
    "applies_to": "同一信息需要进入不同媒体、入口或线下触点的问题。",
    "excludes": "渠道固定且用户主动前来获取完整说明的单一场景。",
    "prompt": "适用：同一信息需要进入不同媒体、入口或线下触点的问题。\n不适用：渠道固定且用户主动前来获取完整说明的单一场景。\n操作：先记录受众在该渠道停留多久、以什么心态进入、下一步能做什么，再确定这个触点只需完成注意、理解、信任或行动中的哪一步；然后按渠道重组信息；最后检查传播是否依赖该渠道不存在的声音、画面、时间或交互能力。\n表达：不要把同一素材机械裁切后称为渠道适配。",
    "enabled": true
  },
  {
    "operator_id": "memory_retrieval",
    "family": "品牌营销与迷因破圈",
    "name": "记忆与提取线索",
    "scope": "industry_general",
    "task_types": [
      "industry_reasoning"
    ],
    "applies_to": "品牌知名但购买时想不起、或传播看过却无法复述的问题。",
    "excludes": "一次性即时转化、用户无需未来回忆的通知。",
    "prompt": "适用：品牌知名但购买时想不起、或传播看过却无法复述的问题。\n不适用：一次性即时转化、用户无需未来回忆的通知。\n操作：先确定受众在什么未来情境下需要想起品牌，再选择能与该情境稳定共同出现的名称、视觉、动作或句式；然后减少互相竞争的记忆点；最后延迟一段时间测试受众能否在没有提示时，从需求情境想起品牌及其核心价值。\n表达：记住广告不等于购买时能想起产品。",
    "enabled": true
  },
  {
    "operator_id": "trust_risk",
    "family": "品牌营销与迷因破圈",
    "name": "信任风险",
    "scope": "industry_general",
    "task_types": [
      "industry_reasoning"
    ],
    "applies_to": "健康、金融、隐私、高价格、长期承诺或陌生品牌传播。",
    "excludes": "低风险、可立即试用且失败成本接近零的轻量选择。",
    "prompt": "适用：健康、金融、隐私、高价格、长期承诺或陌生品牌传播。\n不适用：低风险、可立即试用且失败成本接近零的轻量选择。\n操作：先列出受众最担心的损失和最容易怀疑的承诺，再判断需要透明限制、过程证据、退款退出还是可信第三方；然后把风险说明放在决策发生前；最后检查降低不确定性的措施是否真的约束品牌，而不只是增加保证性口号。\n表达：主动说明边界比重复“值得信赖”更有效。",
    "enabled": true
  },
  {
    "operator_id": "behavior_path",
    "family": "品牌营销与迷因破圈",
    "name": "行为路径",
    "scope": "industry_general",
    "task_types": [
      "industry_reasoning"
    ],
    "applies_to": "传播有明确注册、咨询、试用、购买或复购目标的问题。",
    "excludes": "只做公共信息覆盖且没有后续行为目标的内容。",
    "prompt": "适用：传播有明确注册、咨询、试用、购买或复购目标的问题。\n不适用：只做公共信息覆盖且没有后续行为目标的内容。\n操作：先从最终行为向前倒推受众必须经过的理解、信任和操作步骤，再找出最大退出点及其原因；然后只减少一个关键阻力；最后确认转化提升没有来自误导、默认勾选或把成本推迟到用户无法退出之后。\n表达：每一步只要求受众完成一个清楚动作。",
    "enabled": true
  },
  {
    "operator_id": "incremental_campaign_test",
    "family": "品牌营销与迷因破圈",
    "name": "增量传播试验",
    "scope": "industry_general",
    "task_types": [
      "industry_reasoning"
    ],
    "applies_to": "需要判断某条信息、渠道或创意是否真正带来新增结果。",
    "excludes": "无法形成任何可比较组、也无法观察行为结果的纯曝光项目。",
    "prompt": "适用：需要判断某条信息、渠道或创意是否真正带来新增结果。\n不适用：无法形成任何可比较组、也无法观察行为结果的纯曝光项目。\n操作：先定义没有这次传播时会发生什么，再设置尽可能可比的对照、时间窗和结果指标；然后区分自然增长、渠道重复触达与真正新增；最后根据预先写下的阈值决定扩大、修改或停止，避免只挑好看的互动数字。\n表达：先定义增量，再看总量。",
    "enabled": true
  },
  {
    "operator_id": "objective_ownership",
    "family": "高难度个人战略与人生重大博弈",
    "name": "目标归属",
    "scope": "industry_general",
    "task_types": [
      "industry_reasoning"
    ],
    "applies_to": "职业、学习、关系、迁移或长期投入中不确定自己为何选择的问题。",
    "excludes": "目标由紧急安全需要或明确法定义务决定的情况。",
    "prompt": "适用：职业、学习、关系、迁移或长期投入中不确定自己为何选择的问题。\n不适用：目标由紧急安全需要或明确法定义务决定的情况。\n操作：先分别写出自己想得到的结果、他人期待的结果和为了避免评价而做的事，再用未来一周愿意主动投入的具体行动检查哪项是真目标；然后指出这些目标冲突的决定点；最后只保留愿意承担相应代价的目标。\n表达：不把“应该”自动当作自己的意愿。",
    "enabled": true
  },
  {
    "operator_id": "downside_boundary",
    "family": "高难度个人战略与人生重大博弈",
    "name": "下行边界",
    "scope": "industry_general",
    "task_types": [
      "industry_reasoning"
    ],
    "applies_to": "高不确定、高投入或结果分布很宽的个人决定。",
    "excludes": "损失很小、可立即恢复的日常选择。",
    "prompt": "适用：高不确定、高投入或结果分布很宽的个人决定。\n不适用：损失很小、可立即恢复的日常选择。\n操作：先写出最坏可信结果对现金、健康、时间、关系和职业连续性的影响，再区分可恢复损失与不可恢复损失；然后设置预算、期限和停止条件，使失败不破坏基本生活；最后检查乐观情景是否掩盖了当事人无法承受的单点风险。\n表达：风险用后果和恢复时间说明，不只写概率。",
    "enabled": true
  },
  {
    "operator_id": "option_value",
    "family": "高难度个人战略与人生重大博弈",
    "name": "选择空间价值",
    "scope": "industry_general",
    "task_types": [
      "industry_reasoning"
    ],
    "applies_to": "信息不足但很快要做决定、且部分承诺不可逆的情况。",
    "excludes": "拖延本身会造成更大不可逆损失的紧急决定。",
    "prompt": "适用：信息不足但很快要做决定、且部分承诺不可逆的情况。\n不适用：拖延本身会造成更大不可逆损失的紧急决定。\n操作：先列出立即决定会关闭哪些未来选择，再找出能够用较小成本换取更多信息或延后不可逆承诺的行动；然后为等待设定明确期限和要收集的证据；最后比较保留选择的成本是否低于错误押注的代价。\n表达：保留选择不是无限拖延。",
    "enabled": true
  },
  {
    "operator_id": "evidence_story_split",
    "family": "高难度个人战略与人生重大博弈",
    "name": "证据与自我叙事分离",
    "scope": "industry_general",
    "task_types": [
      "industry_reasoning"
    ],
    "applies_to": "对机会、能力、关系或趋势的判断主要来自强烈感受和零散案例时。",
    "excludes": "已有充分重复数据、当前只需执行明确计划的任务。",
    "prompt": "适用：对机会、能力、关系或趋势的判断主要来自强烈感受和零散案例时。\n不适用：已有充分重复数据、当前只需执行明确计划的任务。\n操作：先把判断拆成可观察事实、自己的解释和希望成立的故事，再主动寻找一个会推翻当前解释的证据；然后根据证据强弱调整行动规模；最后记录什么新信息会让自己改变主意。\n表达：承认不知道比用宏大叙事填空更可靠。",
    "enabled": true
  },
  {
    "operator_id": "resource_allocation",
    "family": "高难度个人战略与人生重大博弈",
    "name": "资源配置",
    "scope": "industry_general",
    "task_types": [
      "industry_reasoning"
    ],
    "applies_to": "时间、金钱、精力分散在多个长期目标之间的问题。",
    "excludes": "当前存在必须立即处理的单一危机。",
    "prompt": "适用：时间、金钱、精力分散在多个长期目标之间的问题。\n不适用：当前存在必须立即处理的单一危机。\n操作：先统计最近四周资源实际流向，而不是计划流向，再为每项投入写出预期结果和最早反馈时间；然后停止或缩小长期没有证据支持的投入；最后把释放的资源集中到一个最能产生新信息或实质进展的方向。\n表达：资源配置以真实日历和账单为准。",
    "enabled": true
  },
  {
    "operator_id": "reversible_commitment",
    "family": "高难度个人战略与人生重大博弈",
    "name": "可逆承诺",
    "scope": "industry_general",
    "task_types": [
      "industry_reasoning"
    ],
    "applies_to": "想尝试新职业、城市、合作或生活方式但不确定匹配度的选择。",
    "excludes": "试验会伤害他人权益、违反合同或制造不可逆安全风险的情况。",
    "prompt": "适用：想尝试新职业、城市、合作或生活方式但不确定匹配度的选择。\n不适用：试验会伤害他人权益、违反合同或制造不可逆安全风险的情况。\n操作：先确定需要验证的核心匹配问题，再设计时间有限、边界清楚且可退出的真实尝试；提前约定成功、继续观察和停止的条件；最后检查试验是否包含真实责任和代价，避免用没有约束的体验误判长期生活。\n表达：小试验要真实，但损失上限要清楚。",
    "enabled": true
  },
  {
    "operator_id": "feedback_horizon",
    "family": "高难度个人战略与人生重大博弈",
    "name": "反馈时间尺度",
    "scope": "industry_general",
    "task_types": [
      "industry_reasoning"
    ],
    "applies_to": "努力与结果间隔较长、容易过早放弃或长期自我安慰的目标。",
    "excludes": "结果即时明确的简单任务。",
    "prompt": "适用：努力与结果间隔较长、容易过早放弃或长期自我安慰的目标。\n不适用：结果即时明确的简单任务。\n操作：先估计最终结果通常多久出现，再寻找更早但确实与结果有关的过程信号；然后规定检查频率，避免每天因噪声改计划；最后设置一个最迟验证点，到期仍无进展时必须重新判断方法或目标。\n表达：过程指标不能只证明自己很忙。",
    "enabled": true
  },
  {
    "operator_id": "identity_cost",
    "family": "高难度个人战略与人生重大博弈",
    "name": "身份成本",
    "scope": "industry_general",
    "task_types": [
      "industry_reasoning"
    ],
    "applies_to": "改变方向会威胁自我认同、社会评价或既有关系的问题。",
    "excludes": "选择与身份和长期关系无关的低成本日常决定。",
    "prompt": "适用：改变方向会威胁自我认同、社会评价或既有关系的问题。\n不适用：选择与身份和长期关系无关的低成本日常决定。\n操作：先写出改变后最担心失去的称呼、认可和关系，再区分真实经济损失与面子损失；然后设计一种不需要否定过去、但允许停止错误投入的叙述和行动；最后检查维护旧身份正在持续消耗什么机会。\n表达：不要求戏剧性切断，优先保护现实安全和关系边界。",
    "enabled": true
  },
  {
    "operator_id": "assumption_domain",
    "family": "数学证明与形式推理",
    "name": "定义域与假设检查",
    "scope": "industry_general",
    "task_types": [
      "formal_reasoning"
    ],
    "applies_to": "需要证明的命题包含变量范围、连续性、独立性、有限性或其他前提。",
    "excludes": "没有待证命题、只要求经验方案或参数建议的任务。",
    "prompt": "适用：需要证明的命题包含变量范围、连续性、独立性、有限性或其他前提。\n不适用：没有待证命题、只要求经验方案或参数建议的任务。\n操作：先逐项写出对象的定义域和所有使用中的假设，再检查每一步推理调用的性质是否由这些假设保证；然后尝试删除一项假设寻找反例；最后区分必要假设、仅为方便的充分假设和完全未使用的假设。\n表达：使用该数学领域的标准术语，不另造方法名称。",
    "enabled": true
  },
  {
    "operator_id": "minimal_counterexample",
    "family": "数学证明与形式推理",
    "name": "最小反例",
    "scope": "industry_general",
    "task_types": [
      "formal_reasoning"
    ],
    "applies_to": "全称命题可能错误，或需要定位证明在哪个最小结构上失败。",
    "excludes": "命题只涉及单个给定实例、无法定义规模或次序。",
    "prompt": "适用：全称命题可能错误，或需要定位证明在哪个最小结构上失败。\n不适用：命题只涉及单个给定实例、无法定义规模或次序。\n操作：先明确反例集合以及用于比较大小的良序量，再假设存在反例并选择最小者；然后利用最小性把它化为更小对象或排除局部结构；最后检查构造出的更小对象是否仍满足原命题全部前提。\n表达：必须说明“最小”按什么度量。",
    "enabled": true
  },
  {
    "operator_id": "invariant_or_measure",
    "family": "数学证明与形式推理",
    "name": "不变量或单调量",
    "scope": "industry_general",
    "task_types": [
      "formal_reasoning"
    ],
    "applies_to": "离散操作、迭代过程、可达性或终止性证明。",
    "excludes": "没有重复状态转移、只需一次代数化简的问题。",
    "prompt": "适用：离散操作、迭代过程、可达性或终止性证明。\n不适用：没有重复状态转移、只需一次代数化简的问题。\n操作：先列全合法状态转移，再寻找每步保持不变的量来排除不可达状态，或寻找每步严格增减且有界的量来证明过程终止；然后逐类验证所有转移；最后处理等号、停滞和边界状态，避免只凭趋势下结论。\n表达：直接称为不变量或单调量，不使用物理隐喻包装。",
    "enabled": true
  },
  {
    "operator_id": "induction_structure",
    "family": "数学证明与形式推理",
    "name": "归纳结构",
    "scope": "industry_general",
    "task_types": [
      "formal_reasoning"
    ],
    "applies_to": "命题按整数、规模、树结构或递归构造自然分层。",
    "excludes": "对象没有可递减结构，或归纳步不能覆盖所有实例。",
    "prompt": "适用：命题按整数、规模、树结构或递归构造自然分层。\n不适用：对象没有可递减结构，或归纳步不能覆盖所有实例。\n操作：先选择能让对象缩小的归纳参数并验证基础情形，再检查普通归纳假设是否足够支持下一步；不足时明确需要强化的附加结论；最后证明每个目标对象都能由已覆盖的更小对象构造出来。\n表达：指出归纳参数和覆盖关系，不只写“由归纳法可得”。",
    "enabled": true
  },
  {
    "operator_id": "bound_sanity",
    "family": "数学证明与形式推理",
    "name": "上下界校验",
    "scope": "industry_general",
    "task_types": [
      "formal_reasoning"
    ],
    "applies_to": "需要估计最坏情况、最好情况、复杂度或误差范围的问题。",
    "excludes": "只要求一个精确数值且不存在近似或规模变化。",
    "prompt": "适用：需要估计最坏情况、最好情况、复杂度或误差范围的问题。\n不适用：只要求一个精确数值且不存在近似或规模变化。\n操作：先用最简单的极端输入得到不可突破的粗界，再检查候选界在小规模、边界值和数量级上是否可能成立；然后分别寻找达到或接近上下界的构造；最后说明界是严格、渐近还是经验性的。\n表达：不把数值模拟结果冒充证明。",
    "enabled": true
  },
  {
    "operator_id": "constructive_existence",
    "family": "数学证明与形式推理",
    "name": "构造性存在",
    "scope": "industry_general",
    "task_types": [
      "formal_reasoning"
    ],
    "applies_to": "需要证明某对象存在，并希望给出可生成或可验证的构造。",
    "excludes": "只要求证明不存在，或已给定唯一对象。",
    "prompt": "适用：需要证明某对象存在，并希望给出可生成或可验证的构造。\n不适用：只要求证明不存在，或已给定唯一对象。\n操作：先把目标性质拆成构造过程中可逐步维持的条件，再从最小对象开始增加元素；每一步检查新元素不会破坏旧条件；最后证明过程能够完成且输出满足全部目标，而不是只展示一个未经一般化的例子。\n表达：区分“找到一个例子”和“给出任意规模的构造”。",
    "enabled": true
  },
  {
    "operator_id": "equivalence_transform",
    "family": "数学证明与形式推理",
    "name": "等价变换",
    "scope": "industry_general",
    "task_types": [
      "formal_reasoning"
    ],
    "applies_to": "原命题直接处理困难，但可能转换为图、代数式、几何对象或优化问题。",
    "excludes": "转换会丢失方向、边界或解的一一对应关系的问题。",
    "prompt": "适用：原命题直接处理困难，但可能转换为图、代数式、几何对象或优化问题。\n不适用：转换会丢失方向、边界或解的一一对应关系的问题。\n操作：先明确原问题的对象、约束和结论，再定义新表示及正向、反向映射；然后分别证明可行性和结论在两种表示间保持；最后检查转换是否引入额外解、遗漏边界情形或只证明了单向蕴含。\n表达：说明等价在哪里成立，不用“升维”“降维”代替映射。",
    "enabled": true
  },
  {
    "operator_id": "proof_gap_audit",
    "family": "数学证明与形式推理",
    "name": "证明缺口审计",
    "scope": "industry_general",
    "task_types": [
      "formal_reasoning"
    ],
    "applies_to": "已有证明、推导或形式化论证需要复核。",
    "excludes": "尚未提出任何可检查论证的开放式构思。",
    "prompt": "适用：已有证明、推导或形式化论证需要复核。\n不适用：尚未提出任何可检查论证的开放式构思。\n操作：先把证明拆成每一步的前提与结论，再标记引用了未证明事实、交换极限与运算、默认存在唯一性或忽略边界的地方；然后优先攻击一旦失败会推翻结论的步骤；最后给出补证、缩小结论范围或明确判错三种结果之一。\n表达：指出具体行和缺失条件，不笼统说“需要更严谨”。",
    "enabled": true
  }
];

export const domainOperatorsMap = new Map(domainOperators.map(o => [o.operator_id, o]));
